admin/announcements.php
admin/attendance.php
admin/badges.php
admin/index.php
admin/membership-plans.php
admin/membership.php
admin/register.php
admin/rewards.php
admin/users.php
assets/css/admin.css
assets/css/styles.css
assets/shared/sidebar.php

- Admin Side bar
- Responsive sidebar 
- Added content in the admin pages 
Closes #4

FE | Admin Sidebar

---

admin/users.php
assets/css/admin.css
assets/css/styles.css

- Created admin user page
- Modified styles.css
- Modified admin.css
Closes #5

FE | Admin User Page

---

admin/announcements.php
admin/users.php
assets/css/admin.css

- Added Admin Announcement Page
- Modified admin.css
- Modified users.php 
- Closes #23

FE | Admin Announcement Page

---

admin/announcements.php
admin/users.php

- Added ADD-EDIT-DELETE modals in announcement page
- Closes #24

FE | Admin Announcement Page - Add, Edit, & Delete Modals

---

admin/attendance.php

- Added Admin Attendance Page
- Modified attendance.php
- Closes #27

FE | Creation of the Admin Attendance Page

---

assets/css/user.css
user/views/profile.php

##🛠️ What was done:
- Added Content for the User Page Profile
- Responsive Page
##📸 Screenshot (if UI changes):
##✅ Checklist:
##📎 Related Issues / Task Link:
- Closes #20

FE | Creation of the User Profile Page

---

admin/rewards.php

- Added content for Rewards Page
- Added the 5 modals
-  Edit Reward Modal
- Add & Delete User Rewards Modal
- Creation of the Add & Delete Rewards Modal
- Tested and Responsive
Modal (isa lang in-attach ko here kasi hahaba and 4 pa yon hehe:
- Closes #29 
- Closes #30 
- Closes #31 
- Closes #32

FE | Added Admin Rewards Page

---

assets/css/web.css
index.php
user/index.php

Changes:
user - index.php
line 63 - add px-1
line 67 - add px-1
line 71 - add px-1
web - index.php
line 73 - btn-primary to btn-login
line 80 - btn-primary to btn-login and remove style="font-family: var(--primaryFont);"
web.css
line 99 to 117 - added .btn-login
line 387 to line 392 - added media query
@binibiningjenna

FE | Modified the Login Button

---

admin/index.php
admin/membership.php
admin/users.php
user/views/dashboard.php

Changes:
- Modified user/views/dashboard.php, for the replacement of 'Gold' to 'Monthly' and the addition of Points
- Modified admin/index.php, for the deletion of pending rewards in the dashboard
- Modified admin/users.php, for the replacement of email and role to 'Points' and addition of Sort by Points
- Modified admin/membership.php, for the replacement of ID to RFID Number

FE | Revisions for user dashboard and admin pages.

---

admin/users.php
assets/php/processes/user/dashboard.php
user/views/dashboard.php

- Implement Member Dashboard with Announcements, Membership Status, and Attendance History
- Membership and attendance data are now displayed based on the current session's user ID ($_SESSION['userID']), ensuring that each user sees only their own information.
- modified:   assets/php/processes/user/dashboard.php
- modified:   user/views/dashboard.php
Closes #39

BE | Implemented Backend for Member Dashboard

---

admin/badges.php
assets/php/modals/admin/badges.php
assets/php/modals/admin/users.php
assets/php/processes/admin/badges.php

- Implement Display Admin Badges Management Page with Badge and User Badge Tables
- Enable Search, Sort, and Safe Deletion for Admin Page User Badge Records
- Implement Badge Management (Add, Edit, Delete) for Admin Badges Table
- modified:   admin/badges.php
- modified:   assets/php/modals/admin/badges.php
- modified:   assets/php/processes/admin/badges.php
Closes #91 
Closes #92 
Closes #93

BE | Implemented Backend Functionality for Badges Page in Admin Panel

---

admin/badges.php
admin/users.php
assets/php/processes/admin/badges.php
assets/php/processes/admin/users.php
assets/php/processes/user/achievements.php
user/index.php
user/views/achievements.php

- Implemented Community Leaderboard with Weekly, Monthly, and All-Time Tabs
Modified Files:
- assets/php/processes/user/achievements.php
- user/index.php
- Renamed: user/views/rewards.php → user/views/achievements.php
----------------------------
Additional Refinements:
- Updated pagination for the Users and Badges pages in the Admin Panel
- Added "State" column to users.php in the Admin Panel
- Updated conditions to display only role = 'user' for the Users and Badges pages in the Admin Panel
- Refined Badges table to support Edit queries with image deletion
##📸 Screenshot
<br>
- USER ID = 3 (LENA): Rank is Displayed Even When Outside Top 5 (e.g., Weekly: 7th, Monthly: Top 1, All-Time: Top 2)
<br><br><br>
- Refined Badges table to support Edit queries with image deletion
<br><br><br>
- …

BE | Refinements on Other Pages and Backend Implementation for the Leaderboard in the User Dashboard

---

admin/index.php
assets/php/classes/classes.php
assets/php/processes/user/dashboard.php

1. Implemented Interactive Chart for Member Age Distribution
2. Updated backend functionality for the Attendance Chart, Membership Distribution Chart, and Age Distribution Chart to align with the updated renewal process, which now includes copies of previous or old memberships of gym members.
3. Added a dropdown option to filter by Active and All, allowing filtering of active users and active memberships of gym members.
4. Updated the User Dashboard to ensure that only the latest membership and its expiry date are displayed.
5. Ensured that all JS charts display only user records, excluding admin accounts.
6. Updated the year dropdown from attendance-based to use the start years of user_memberships, applicable to all JS charts.
7. **Note**: To avoid duplicate records based on startDate, …

BE | Developed backend functionality for the Age Distribution JS Chart

---

admin/index.php
admin/membership.php
admin/renewal.php
assets/js/admin.js
assets/js/user.js
assets/php/classes/classes.php
assets/php/processes/admin/index.php
assets/php/processes/admin/membership.php
assets/php/processes/admin/renewal.php
assets/php/processes/user/workout.php
assets/shared/connect.php
user/views/workout.php

- Modified admin/index.php, assets/js/admin.js, assets/php/processes/admin/index.php for the loading of top 10 active members
- Closes #122

BE | Display of Top 10 Active Members

---

admin/announcements.php
assets/js/user.js
assets/php/classes/classes.php
assets/php/modals/admin/membership.php
assets/php/processes/admin/announcement.php
assets/php/processes/admin/index.php
assets/php/processes/admin/membership.php
user/views/workout.php

- Check the files changed for the files modified for the number 1, 2, 4, 10, and 12 for the revision of backend
Number 1:
Number 02:
Number 04:
Number 10:
Number 11 (Changes for the admin side):
Number 12:

BE | Revisions Implemented

---

assets/php/classes/classes.php
assets/php/modals/admin/badges.php
assets/php/processes/admin/badges.php
assets/php/processes/user/achievements.php
user/views/achievements.php
user/views/dashboard.php

1. Admin – Dashboard (Age Distribution): Hide the legend if no data is available on the graph. (6)
2. Admin – Badges Page (Create & Edit): Prevent duplicate badge entries in the table. (9)
3. User – Announcements Page: Display the creation date of each announcement to help users identify if an announcement is new or old. (11)
4. Admin – Badges Page (Create & Edit): Disallow the use of special characters in input fields. (12)
5. Admin – Badges Page (Create & Edit): Show a proper error message when an invalid file type is uploaded: 
- "Invalid file type. Please upload an image in JPG or PNG format only." (13)
6. Community Leaderboard:  
- Set “All Time” as the default view to ensure records are displayed consistently.
- Display a “No records found” message when there are no top users …

BE | Admin & User Enhancements: Dashboard Legend Logic, Badge Validation, Announcement Date, Leaderboard Defaults

---

assets/js/membership-plans.js
assets/php/modals/admin/membership-plans.php
assets/php/processes/admin/membership-plans.php

PR Title: BE | Membership Plans fixes
Description Template: 
- Adjusted membership-plans page modal backdrop when adding a new plan.
[Attach screenshot here]
- Closes #126

BE | Membership Plans fixes

---

admin/attendance.php
assets/php/modals/user/workout.php
checkin.php

Description Template: 
modified:   admin/attendance.php
modified:   assets/php/modals/user/workout.php
modified:   checkin.php
**01**
**02**
- nilakkihan ko na rin yung display sa desktop para makita rin ng gym members ng mas madali just incase malayo sila sa screen ng laptop.
**03**

BE | Enhancement

---

assets/css/user.css
user/index.php
user/views/dashboard.php

- I enhanced the text size of long announcements to fit small screens for better responsiveness.

BE | Minor Refinements for Responsiveness

---

admin/renewal.php
assets/php/processes/admin/membership.php

- edited renewal.php for the new integration of database

BE | Renewal revision for new database

---

assets/php/processes/admin/attendance.php

PR Title: BE | Updated search function for admin attendance page
Description Template: 
- Updated the admin attendance page search function

BE | Updated search function for admin attendance page

---

admin/badges.php
admin/users.php
assets/css/user.css
assets/php/modals/admin/badges.php
user/index.php
user/views/profile.php

1. Resized announcement header
2. User’s name displayed properly in user badge deletion
3. No overlap with long URLs for icons in badges
4. Search interval updated to 1000 ms (1 second)

BE | Refinements

---

admin/attendance.php
assets/js/login.js
assets/js/membership-plans.js
assets/php/modals/admin/membership-plans.php
assets/php/processes/admin/attendance.php
assets/php/processes/admin/membership-plans.php
assets/php/processes/forgotpassword/phpmailer.php
assets/php/processes/login.php
index.php
user/index.php

PR Title: BE | Admin and user side revisions
Description Template: 
**01**
- Arranged error feedbacks layout on membership plans page
**02**
- Updated the search focus to 2seconds
**03**
- May placeholder naman ng date sa birthday field sa side ko
**04**
- Updated the login process to check if email is not on db
**05**
- If the admin deleted a user account, the logged in user will be directed to login page to avoid N/A values.

Admin and user side revisions

---

admin/membership.php
admin/renewal.php
assets/php/processes/admin/membership.php

- Made the search function for the membership be 2 secs
- Refined the deletion function of the membership 
- Refined the words used to describe the else option for search function in renewal
Membership deletion makes the state be 'Inactive' function:

BE | Few refinements to membership page functions

---

admin/membership.php
assets/php/processes/admin/membership.php

- Made membership deletion reset the points to 0.
- Made the edit not allow the change of the same RFID value
Reset Points to 0:
No same RFID value:

BE | Membership page refinement
